services:
  surch-app: # Este es el nombre que usar√°s en el panel de Nginx Proxy Manager
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - n8n-docker_default

networks:
  n8n-docker_default:
    external: true
